// PATIENTS
export const FETCH_PATIENT_REQUEST = "FETCH_PATIENT_REQUEST";
export const FETCH_PATIENT_SUCCESS = "FETCH_PATIENT_SUCCESS";
export const FETCH_PATIENT_FAILED = "FETCH_PATIENT_FAILED";

export const VALID_PATIENT_REQUEST = "VALID_PATIENT_REQUEST";
export const VALID_PATIENT_SUCCESS = "VALID_PATIENT_SUCCESS";
export const VALID_PATIENT_FAILED = "VALID_PATIENT_FAILED";

export const LOGIN_PATIENT_REQUEST = "LOGIN_PATIENT_REQUEST";
export const LOGIN_PATIENT_SUCCESS = "LOGIN_PATIENT_SUCCESS";
export const LOGIN_PATIENT_FAILED = "LOGIN_PATIENT_FAILED";

export const LOGOUT_PATIENT_REQUEST = "LOGOUT_PATIENT_REQUEST";
export const LOGOUT_PATIENT_SUCCESS = "LOGOUT_PATIENT_SUCCESS";
export const LOGOUT_PATIENT_FAILED = "LOGOUT_PATIENT_FAILED";


// APPOINTMENT
export const FETCH_APPOINTMENT_REQUEST = "FETCH_APPOINTMENT_REQUEST";
export const FETCH_APPOINTMENT_SUCCESS = "FETCH_APPOINTMENT_SUCCESS";
export const FETCH_APPOINTMENT_FAILED = "FETCH_APPOINTMENT_FAILED";

// SERVICES
export const FETCH_SERVICES_REQUEST = "FETCH_SERVICES_REQUEST";
export const FETCH_SERVICES_SUCCESS = "FETCH_SERVICES_SUCCESS";
export const FETCH_SERVICES_FAILED = "FETCH_SERVICES_FAILED";

// DENTIST
export const FETCH_DENTIST_REQUEST = "FETCH_DENTIST_REQUEST";
export const FETCH_DENTIST_SUCCESS = "FETCH_DENTIST_SUCCESS";
export const FETCH_DENTIST_FAILED = "FETCH_DENTIST_FAILED";